### ISSUE TITLE
css fundament error

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-tagebuch#32]
There is an error in the fundament min css for the menu in screen width between 992px and 1200px when the menu is a dropdown list. see here:

<img width="696" alt="Bildschirmfoto 2020-03-22 um 21 55 37" src="https://user-images.githubusercontent.com/11441262/77260411-29bfa900-6c88-11ea-9a27-8f1100912487.png">
<img width="799" alt="Bildschirmfoto 2020-03-22 um 21 55 21" src="https://user-images.githubusercontent.com/11441262/77260412-2af0d600-6c88-11ea-94fa-fb58d673ba1c.png">

not the complete menu is shown compared to a screen-width of over 1200). And the project logo is jumping.

(If you should fix it please let me know, I have the same error at the Schnitzler-letters and I can't pinpoint it)

**Comment by martinantonmueller** [comment]
Actually it is hidden somewhere in fundament.min.css. As this file is missing from the current base-app it seems as this bug is schnitzler-tagebuch and schnitzler-letter-specific

**Comment by csae8092** [comment]
@babslgam or @asilcetin could you please take a look? Thanks you!

**Comment by asilcetin** [comment]
I'll look into this, thanks for reporting.

**Comment by asilcetin** [comment]
After inspecting I realize that this issue was already fixed some time ago in fundament: https://github.com/acdh-oeaw/fundament/commit/339a8976e8545cada5600b45c0f5f0ff180dcca9

You might solve the problem by updating your css file (https://schnitzler-briefe.acdh-dev.oeaw.ac.at/pages/$app-root/resources/css/fundament.min.css) with this one: https://github.com/acdh-oeaw/fundament/blob/master/dist/fundament/css/fundament.min.css

**Comment by csae8092** [comment]
replacing the css needs some small other adaptions

**Comment by csae8092** [comment]
of course changing the base-css to default fundament causes some other issues than those fixed above; I guess the text in the title image was not always that hardly readable. But since this can be fixed by adjusting the app-specific css (https://github.com/acdh-oeaw/schnitzler-tagebuch/blob/master/resources/css/style.css) I leave it to those who care to fix those issues

**Comment by martinantonmueller** [comment]
Seems to work now, so I close this issue
